### ISSUE TITLE
ios 8.3 safe mode trigger

### ISSUE THREAD

**Issue by mailinglists35** [JonasGessner/CCLoader#14]
CCLoader sends device into safe mode on iOS 8.3.

**Comment by davidoff00008** [comment]
uuh

**Comment by mailinglists35** [comment]
what's the point of enabling github issues of a project when you don't even bother to read reported issues?

**Comment by JonasGessner** [comment]
There's too many details in your bug report. I still haven't finished reading your bug report until the end, it's just too long!

**Comment by JonasGessner** [comment]
Jokes aside, the least you could have done was attach a crash log, like this gentleman did: https://github.com/JonasGessner/CCLoader/issues/12

An issue like this is useless, unless you provide more information. I also haven't had any other reports of crashes on iOS 8.3, which narrows it down to an incompatibility with another tweak.

**Comment by mailinglists35** [comment]
well I no longer have 8.3 since I've immediately updated to 8.4 when jb was out.
tbh I have even forgotten about this until the second comment appeared in my notifications... if you want people to send logs, at least you could say that in a Contributing.md file like this https://github.com/isaacs/github/issues/99#issuecomment-24584307
